#include <kernel/keyboard.h>

char kbd_reg_keycodes[] = {
	[0x01] = KEY_ESCAPE,
	         KEY_1,
	         KEY_2,
	         KEY_3,
	         KEY_4,
	         KEY_5,
	         KEY_6,
	         KEY_7,
	         KEY_8,
	         KEY_9,
	         KEY_0,
	         KEY_DASH,
	         KEY_EQUAL,
	         KEY_BACKSPACE,
	         KEY_TAB,
	         KEY_Q,
	         KEY_W,
	         KEY_E,
	         KEY_R,
	         KEY_T,
	         KEY_Y,
	         KEY_U,
	         KEY_I,
	         KEY_O,
	         KEY_P,
	         KEY_OPENING_SQUARE_BRACKET,
	         KEY_CLOSING_SQUARE_BRACKET,
	         KEY_ENTER,
	         KEY_LEFT_CTRL,
	         KEY_A,
	         KEY_S,
	         KEY_D,
	         KEY_F,
	         KEY_G,
	         KEY_H,
	         KEY_J,
	         KEY_K,
	         KEY_L,
	         KEY_COLON,
	         KEY_SINGLE_QUOTE,
	         KEY_BACKTICK,
	         KEY_LEFT_SHIFT,
	         KEY_BACKSLASH,
	         KEY_Z,
	         KEY_X,
	         KEY_C,
	         KEY_V,
	         KEY_B,
	         KEY_N,
	         KEY_M,
	         KEY_COMMA,
	         KEY_DOT,
	         KEY_SLASH,
	         KEY_RIGHT_SHIFT,
	         KEY_KEYPAD_WILDCARD,
	         KEY_LEFT_ALT,
	         KEY_SPACE,
	         KEY_CAPS_LOCK,
	         KEY_F1,
	         KEY_F2,
	         KEY_F3,
	         KEY_F4,
	         KEY_F5,
	         KEY_F6,
	         KEY_F7,
	         KEY_F8,
	         KEY_F9,
	         KEY_F10,
	         KEY_NUMLOCK,
	         KEY_SCROLLLOCK,
	         KEY_KEYPAD_7,
	         KEY_KEYPAD_8,
	         KEY_KEYPAD_9,
	         KEY_KEYPAD_DASH,
	         KEY_KEYPAD_4,
	         KEY_KEYPAD_5,
	         KEY_KEYPAD_6,
	         KEY_KEYPAD_PLUS,
	         KEY_KEYPAD_1,
	         KEY_KEYPAD_2,
	         KEY_KEYPAD_3,
	         KEY_KEYPAD_0,
	         KEY_KEYPAD_DOT,
	[0x57] = KEY_F11,
             KEY_F12,
};

char kbd_ext_keycodes[] = {
	[0x10] = KEY_MULTIMEDIA_PREVIOUS_TRACK,
	[0x19] = KEY_MULTIMEDIA_NEXT_TRACK,
	[0x1C] = KEY_KEYPAD_ENTER,
	         KEY_RIGHT_CTRL,
	[0x20] = KEY_MULTIMEDIA_MUTE,
         	 KEY_MULTIMEDIA_CALCULATOR,
         	 KEY_MULTIMEDIA_PLAY,
	[0x24] = KEY_MULTIMEDIA_STOP,
	[0x2E] = KEY_MULTIMEDIA_VOLUME_DOWN,
	[0x30] = KEY_MULTIMEDIA_VOLUME_UP,
	[0x32] = KEY_MULTIMEDIA_HOME_WWW,
	[0x35] = KEY_KEYPAD_SLASH,
	[0x38] = KEY_RIGHT_ALT,
	[0x47] = KEY_HOME,
             KEY_CURSOR_UP,
             KEY_PAGE_UP,
	[0x4B] = KEY_CURSOR_LEFT,
	[0x4D] = KEY_CURSOR_RIGHT,
	[0x4F] = KEY_END,
	         KEY_CURSOR_DOWN,
	         KEY_PAGE_DOWN,
			 KEY_INSERT,
			 KEY_DELETE,
	[0x5B] = KEY_LEFT_GUI,
	         KEY_RIGHT_GUI,
	         KEY_APPS,
             KEY_ACPI_POWER,
			 KEY_ACPI_SLEEP,
	[0x63] = KEY_ACPI_WAKE,
	[0x65] = KEY_MULTIMEDIA_WWW_SEARCH,
             KEY_MULTIMEDIA_WWW_FAVORITES,
             KEY_MULTIMEDIA_WWW_REFRESH,
             KEY_MULTIMEDIA_WWW_STOP,
             KEY_MULTIMEDIA_WWW_FORWARD,
             KEY_MULTIMEDIA_WWW_BACK,
             KEY_MULTIMEDIA_MY_COMPUTER,
             KEY_MULTIMEDIA_EMAIL,
             KEY_MULTIMEDIA_MEDIA_SELECT,
};
